name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      envioronment:
        description: "Select an envioronment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production
      version:
        description: "Select a deploy version"
        required: true
        type: string

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/checkout@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Deploy application
        run: |
          echo "選択された環境: ${{github.event.inputs.environment}}"
          echo "指定されたバージョン: ${{github.event.inputs.version}}"

      - name: Run tests
        run: npm test
